# Generated by Django 2.0.5 on 2018-05-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nz_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmo', models.IntegerField(blank=True, null=True)),
                ('chom', models.IntegerField(blank=True, null=True)),
                ('names', models.CharField(blank=True, max_length=100)),
                ('heights', models.FloatField(blank=True, null=True)),
                ('types', models.CharField(blank=True, max_length=100)),
                ('cloud_base_m', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'NZ_table',
            },
        ),
        migrations.CreateModel(
            name='queensland_weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmo_id', models.BigIntegerField(blank=True, null=True)),
                ('bom_id', models.BigIntegerField(blank=True, null=True)),
                ('tz', models.CharField(blank=True, max_length=100, null=True)),
                ('station_name', models.CharField(blank=True, max_length=100, null=True)),
                ('station_height', models.FloatField(blank=True, null=True)),
                ('station_type', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('forecast_district_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('period_index', models.BigIntegerField(blank=True, null=True)),
                ('time_utc', models.CharField(blank=True, max_length=100, null=True)),
                ('time_local', models.CharField(blank=True, max_length=100, null=True)),
                ('wind_src', models.CharField(blank=True, max_length=100, null=True)),
                ('level_index', models.IntegerField(blank=True, null=True)),
                ('level_type', models.CharField(blank=True, max_length=100, null=True)),
                ('apparent_temp', models.FloatField(blank=True, null=True)),
                ('cloud', models.CharField(blank=True, max_length=100, null=True)),
                ('cloud_base_m', models.IntegerField(blank=True, null=True)),
                ('cloud_oktas', models.IntegerField(blank=True, null=True)),
                ('cloud_type_id', models.IntegerField(blank=True, null=True)),
                ('cloud_type', models.CharField(blank=True, max_length=100, null=True)),
                ('delta_t', models.FloatField(blank=True, null=True)),
                ('gust_kmh', models.IntegerField(blank=True, null=True)),
                ('wind_gust_spd', models.IntegerField(blank=True, null=True)),
                ('air_temperature', models.FloatField(blank=True, null=True)),
                ('dew_point', models.FloatField(blank=True, null=True)),
                ('pres', models.FloatField(blank=True, null=True)),
                ('msl_pres', models.FloatField(blank=True, null=True)),
                ('qnh_pres', models.FloatField(blank=True, null=True)),
                ('rain_hour', models.FloatField(blank=True, null=True)),
                ('swell_dir', models.CharField(blank=True, max_length=100, null=True)),
                ('swell_height', models.FloatField(blank=True, null=True)),
                ('swell_period', models.IntegerField(blank=True, null=True)),
                ('rain_ten', models.FloatField(blank=True, null=True)),
                ('rel_humidity', models.IntegerField(blank=True, null=True)),
                ('sea_height', models.CharField(blank=True, max_length=100, null=True)),
                ('vis_km', models.FloatField(blank=True, null=True)),
                ('weather', models.CharField(blank=True, max_length=100, null=True)),
                ('wind_dir', models.CharField(blank=True, max_length=100, null=True)),
                ('wind_dir_deg', models.IntegerField(blank=True, null=True)),
                ('wind_spd_kmh', models.IntegerField(blank=True, null=True)),
                ('wind_spd', models.IntegerField(blank=True, null=True)),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('rainfall_24hr', models.FloatField(blank=True, null=True)),
                ('maximum_air_temperature', models.FloatField(blank=True, null=True)),
                ('minimum_air_temperature', models.FloatField(blank=True, null=True)),
                ('maximum_gust_spd', models.IntegerField(blank=True, null=True)),
                ('maximum_gust_kmh', models.IntegerField(blank=True, null=True)),
                ('maximum_gust_dir', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'queensland_weather_table',
            },
        ),
    ]
